[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
{% if is_fullstack -%}
server = { workspace = true }

[features]
server = ["server/server"] # Re-export the server feature from the server crate for any server specific dependencies
{%- endif %}
